name: Install Istioctl

on:
  push:
    branches:
      - main

jobs:
  install-istioctl:
    runs-on: ubuntu-latest

    steps:

      - name: Download istioctl
        shell: pwsh
        run: |
          $istio_version = "1.18.2"
          $url = "https://github.com/istio/istio/releases/download/$istio_version/istio-$istio_version-linux-amd64.tar.gz"
          Invoke-WebRequest -Uri $url -OutFile "istio.tar.gz"
          mkdir test
          tar -xzf "istio.tar.gz" -C ./test
          cd ./test
          ls -la
          cd ..
          chmod -R 755 ./test
          cd ./test
          ls -la
          cd istio-$istio_version
          ls -la
          istioctl version
          pwd


      - name: Set PATH
        run: |
          echo "export PATH=\$PATH:/usr/local/bin:./test" >> $GITHUB_ENV
        
#      - name: Add istioctl to PATH
#        shell: pwsh
#        run: |
#          $istioPath = "$env:RUNNER_TEMP/istio-$istio_version/bin"
#          echo "##[add-path]$istioPath"

      - name: Verify istioctl installation
        shell: pwsh
        run: |
          istioctl version
