name: Install Istioctl

on:
  push:
    branches:
      - main

jobs:
  install-istioctl:
    runs-on: ubuntu-latest

    steps:

      - name: Download istioctl
        shell: pwsh
        run: |
          $istio_version = "1.18.2"
          $url = "https://github.com/istio/istio/releases/download/$istio_version/istio-$istio_version-linux-amd64.tar.gz"
          Invoke-WebRequest -Uri $url -OutFile "istio.tar.gz"
          
          echo $PWD
          
          mkdir test
          tar -xzf "istio.tar.gz" -C ./test
          chmod -R 755 ./test
          cd ./test/istio-$istio_version/bin
          ls -la
          
          # Add istioctl directory to the PATH
          $env:PATH = "$PWD:$env:PATH"

          # Check if istioctl works by calling it directly
          ./istioctl version
          
          # After updating PATH, test istioctl again without specifying path
          istioctl version
