name: Install Istioctl

on:
  push:
    branches:
      - main

jobs:
  install-istioctl:
    runs-on: ubuntu-latest

    steps:

      - name: Download istioctl
        shell: pwsh
        run: |
          $istio_version = "1.18.2"
          $url = "https://github.com/istio/istio/releases/download/$istio_version/istio-$istio_version-linux-amd64.tar.gz"
          Invoke-WebRequest -Uri $url -OutFile "istio.tar.gz"
          
          echo $PWD
          
          mkdir test
          tar -xzf "istio.tar.gz" -C ./test
          chmod -R 755 ./test
          cd ./test/istio-$istio_version/bin
          ls -la
          
          # Add istioctl directory to the PATH
          $env:PATH = "${$PWD}:$env:PATH"

          # Check if istioctl works by calling it directly
          echo $PWD
          ./istioctl version
          

      - name: Add istioctl to PATH
        shell: bash
        run: |
          echo "Adding istioctl to PATH"
          export PATH=$PWD/test/istio-1.18.2/bin:$PATH
          
          # Test istioctl again after PATH modification
          istioctl version
          
      - name: Cache istioctl
        uses: actions/cache@v3
        with:
          path: ./test/istio-1.18.2/bin
          key: istio-1.18.2


  istioctl-version-check:
    runs-on: ubuntu-latest
    needs: install-istioctl

    steps:
      - name: Check inital 
        shell: bash
        run: |
          pwd
          ls -la
      - name: Restore istioctl from cache
        uses: actions/cache@v3
        with:
          path: ./test/istio-1.18.2/bin
          key: istio-1.18.2
      - name: cache restore
        shell: bash
        run: |
          pwd
          ls -la
          cd ./test/istio-1.18.2/bin
          ls -la
          
      - name: Add istioctl to PATH
        shell: bash
        run: |
          chmod -R 755 ./test/istio-1.18.2/bin
          export PATH=$PWD/test/istio-1.18.2/bin:$PATH

      - name: Verify Istioctl Version
        run: |
          istioctl version
