name: Install Istioctl Windows

on:
  push:
    branches:
      - main

jobs:
  install-istioctl:
    runs-on: windows-latest

    steps:

      - name: Download istioctl Windows
        shell: pwsh
        run: |
          $istio_version = "1.21.6"
          # https://github.com/istio/istio/releases/download/1.21.6/istioctl-1.21.6-win-amd64.zip
            # https://github.com/istio/istio/releases/download/1.21.6/istio-1.21.6-linux-amd64.tar.gz
            $url = "https://github.com/istio/istio/releases/download/$istio_version/istioctl-$($istio_version)-win-amd64.zip"
            Invoke-WebRequest -Uri $url -OutFile "istio.zip"
            
            echo $PWD
            
            mkdir test
            tar -xzf "istio.zip" -C ./test
            chmod -R 755 ./test
            cd ./test
            #ls -la
            Get-ChildItem -Force | Format-List
            # Add istioctl directory to the PATH
            $env:PATH = "${$PWD}:$env:PATH"
            # Check if istioctl works by calling it directly
            echo $PWD
            .\istioctl.exe version

          
          

      - name: Add istioctl to PATH
        shell: pwsh
        run: |
          echo "Adding istioctl to PATH"
            # export PATH=$PWD/test:$PATH
            $env:PATH = "$($pwd)\test;$env:PATH"
            [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH, [System.EnvironmentVariableTarget]::Process)
            # echo "$PWD/test" >> $GITHUB_PATH
            # Test istioctl again after PATH modification
            istioctl version
          
      - name: Cache istioctl
        uses: actions/cache@v3
        with:
          path: ./test
          key: istio-1.21.6-win


  istioctl-version-check:
    runs-on: ubuntu-latest
    needs: install-istioctl

    steps:
      - name: Check inital 
        shell: pwsh
        run: |
          pwd
          Get-ChildItem -Force | Format-List
          
      - name: Restore istioctl from cache
        uses: actions/cache@v3
        with:
          path: ./test
          key: istio-1.21.6-win
          
      - name: cache restore
        shell: pwsh
        run: |
          pwd
          Get-ChildItem -Force | Format-List
          cd ./test
          Get-ChildItem -Force | Format-List
          .\istioctl.exe version
          
      - name: Add istioctl to PATH
        shell: pwsh
        run: |
          # chmod -R 755 ./test
          $testPath = "$($pwd)\test"
          Add-Content -Path $env:GITHUB_PATH -Value $testPath
          # Test istioctl again after PATH modification
          istioctl version

          

      - name: Test istioctl version
        run: |
          istioctl version
          
